In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Iris.csv")

In [10]:
x = pd.DataFrame(df.iloc[:,1:-1])
y = pd.DataFrame(df.iloc[:,-1])

In [11]:
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [5]:
y.head()

       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

y_enc = pd.DataFrame(le.fit_transform(y.iloc[:,0]))

print(le.classes_)

y_enc.head()

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

     0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]