In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Writing Linear Regression from scratch

In [2]:
def mean(a):
    res = np.sum(a, axis=0) / len(a)
    return res

def variance(ai, avg):
    return ai - avg

def slope(var_x, var_y):
    res = np.sum(var_x*var_y) / np.sum(np.square(var_x))
    return res

def intercept(x_avg, y_avg, slope):
    return y_avg - slope*x_avg

def LinearRegression(x, y):

    x_avg = mean(x)
    # print(x_avg)
    y_avg = mean(y)
    # print(y_avg)

    var_x = np.array(variance(x, x_avg))
    # print(var_x)

    var_y = np.array(variance(y, y_avg))
    # print(var_y)

    w = slope(var_x, var_y)
    print(w)

    b = intercept(x_avg, y_avg, w)
    print(b)

    return w, b

def pred(w, b, x):
    return w * x + b

def error(test, pred):
    return test - pred

In [3]:
df = pd.read_csv("Salary_dataset.csv")

In [4]:
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 848.0 bytes

In [6]:
df.describe()

       Unnamed: 0  YearsExperience         Salary
count   30.000000        30.000000      30.000000
mean    14.500000         5.413333   76004.000000
std      8.803408         2.837888   27414.429785
min      0.000000         1.200000   37732.000000
25%      7.250000         3.300000   56721.750000
50%     14.500000         4.800000   65238.000000
75%     21.750000         7.800000  100545.750000
max     29.000000        10.600000  122392.000000

In [7]:
data = np.loadtxt("Salary_dataset.csv", delimiter=",", skiprows=1)

x = data[:,1]
y = data[:,2]

len_data = int(len(data))
x_train = data[: int(len_data*0.8),1]
y_train = data[: int(len_data*0.8),2]
x_test = data[int(len_data*0.8):,1]
y_test = data[int(len_data*0.8):,2]

In [8]:
w, b = LinearRegression(x_train, y_train)

10052.786167455994
22655.57005629524

In [9]:
y_pred = pred(w, b, x_test)

In [10]:
y_pred

array([111120.08832991, 114135.92418014, 119162.31726387, 120167.59588062,
       127204.54619784, 129215.10343133])

In [11]:
y_test

array([109432., 105583., 116970., 112636., 122392., 121873.])

In [12]:
def MSE(test, pred):
    return np.sum(np.square(test - pred)) / len(test)

def RMSE(test, pred):
    return np.sqrt(MSE(test, pred))

def MAE(test, pred):
    return np.sum(np.abs(test - pred)) / len(test)

def R2(test, pred, y):
    return 1 - ((np.sum(np.square(test - pred)))/(np.sum(np.square(test - mean(y)))))

In [13]:
print("mse=", MSE(y_test, y_pred))
print("rmse=", RMSE(y_test, y_pred))
print("mae=", MAE(y_test, y_pred))
print("r2=", R2(y_test, y_pred, y))

mse= 35766738.239658274
rmse= 5980.529929668296
mae= 5353.262547285041
r2= 0.9768457032355965

## Using Sklearn library for comparison

In [14]:
# df = pd.read_csv("Salary_dataset.csv")
# x = pd.DataFrame(df.iloc[:,1:-1])
# y = pd.DataFrame(df.iloc[:, -1])

In [15]:
# from sklearn.model_selection import train_test_split

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
# from sklearn.linear_model import LinearRegression

# model = LinearRegression()
# model.fit(x_train, y_train)
# y_pred = model.predict(x_test)

In [17]:
# from sklearn.metrics import r2_score
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import root_mean_squared_error
# from sklearn.metrics import mean_absolute_error

# MSE = mean_squared_error(y_test, y_pred)
# R2 = r2_score(y_test, y_pred)
# RMSE = root_mean_squared_error(y_test, y_pred)
# MAE = mean_absolute_error(y_test, y_pred)

# print("MSE=", MSE)
# print("MAE=", MAE)
# print("RMSE", RMSE)
# print("R2=", R2)

# print("Intercept:", model.intercept_)
# print("Coefficients:", model.coef_)

## Using Gradient Descent

In [18]:
data = np.loadtxt("Salary_dataset.csv", delimiter=",", skiprows=1)

x = data[:,1]
y = data[:,2]

In [28]:
learningRate = 0.0001
epochs = 100000

w = 0
b = 0

for i in range(epochs):

    y_pred = w * x + b

    err = (y_pred - y)

    dw = (2 / len(x)) * np.sum(err * x)
    db = (2 / len(x)) * np.sum(err)

    w = w - learningRate*dw
    b = b - learningRate*db

In [29]:
w

np.float64(9505.263072518806)